export type { AppRouter } from "./app-router"
export type { Pageable } from "./query"

export type * as ArticleRouter from "./modules/article/article-router"
export type * as AttendanceRouter from "./modules/event/attendance-router"
export type * as EventRouter from "./modules/event/event-router"
export type * as AuditLogRouter from "./modules/audit-log/audit-log-router"
export type * as CompanyRouter from "./modules/company/company-router"
export type * as FeedbackRouter from "./modules/feedback-form/feedback-router"
export type * as GroupRouter from "./modules/group/group-router"
export type * as JobListingRouter from "./modules/job-listing/job-listing-router"
export type * as MarkRouter from "./modules/mark/mark-router"
export type * as OfflineRouter from "./modules/offline/offline-router"
export type * as PersonalMarkRouter from "./modules/mark/personal-mark-router"
export type * as WorkspaceRouter from "./modules/workspace-sync/workspace-router"
export type * as UserRouter from "./modules/user/user-router"
