#!/usr/bin/env just --justfile
export PATH := "./node_modules/.bin:" + env_var('PATH')

build env:
  docker build --platform linux/amd64 -t brevduen:latest -f Dockerfile ../..

push env:
  docker tag brevduen:latest 891459268445.dkr.ecr.eu-north-1.amazonaws.com/brevduen-{{env}}:latest
  docker push 891459268445.dkr.ecr.eu-north-1.amazonaws.com/brevduen-{{env}}:latest

release env: (build env) (push env)
  aws lambda update-function-code --function-name brevduen-{{env}} \
    --image-uri 891459268445.dkr.ecr.eu-north-1.amazonaws.com/brevduen-{{env}}:latest \
    --region eu-north-1
