# This action starts a local PostgreSQL service and creates a database user and database, migrates, and generates Prisma
# client and TypedSQL artifacts locally.

name: Setup database
description: Start a local Postgres database.
runs:
  using: composite
  steps:
    - name: Start local PostgreSQL service
      shell: bash
      run: |
        sudo service postgresql start
        until pg_isready -U postgres; do sleep 1; done

    - name: Create database user and database
      shell: bash
      run: |
        sudo -u postgres psql -c "CREATE USER ow WITH PASSWORD 'owpassword123';"
        sudo -u postgres psql -c "CREATE DATABASE ow WITH OWNER ow;"

    - uses: pnpm/action-setup@v2
      with:
        version: 10.28.2
    - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
      with:
        node-version: 22.21.1
        cache: 'pnpm'
    - name: Install dependencies from pnpm lockfile
      shell: bash
      run: pnpm install --frozen-lockfile

    - name: Export database URL
      shell: bash
      run: echo "DATABASE_URL=postgresql://ow:owpassword123@localhost:5432/ow" >> "$GITHUB_ENV"

    - name: Apply Prisma migrations
      shell: bash
      run: pnpm -F @dotkomonline/db prisma migrate deploy

    - name: Generate Prisma Client and TypedSQL
      shell: bash
      run: pnpm -F @dotkomonline/db generate
