name: Build & deploy monoweb/kvittering-frontend
inputs:
  git-hash:
    description: 'Git hash to build'
    required: true
  deploy:
    description: 'Deploy the built site to AWS S3'
    required: false
    default: false
runs:
  using: composite
  steps:
    - name: Install local GitHub Actions
      uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      with:
        fetch-depth: 1
        sparse-checkout: '.github'
        sparse-checkout-cone-mode: true
    - uses: ./.github/actions/internal/doppler-secrets
      id: acquire-secrets
      with:
        project: monoweb-kvittering-frontend
        config: prd

    - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      with:
        fetch-depth: 1
        ref: ${{ inputs.git-hash }}
    - uses: pnpm/action-setup@v2
      with:
        version: 9.15.9
    - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
      with:
        node-version: 22.18.0
        cache: 'pnpm'
    - name: Build frontend
      shell: bash
      working-directory: apps/kvittering-frontend
      run: pnpm install && pnpm build

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4
      with:
        aws-region: eu-north-1
        role-to-assume: arn:aws:iam::891459268445:role/monoweb-prd-kvittering-frontend-ci-role
    - name: Deploy to S3
      if: ${{ inputs.deploy == 'true' }}
      shell: bash
      run: |
        aws s3 sync apps/kvittering-frontend/dist "s3://kvittering.online.ntnu.no" \
          --exclude "*" \
          --include "*.html" \
          --content-type "text/html"
        aws s3 sync apps/kvittering-frontend/dist "s3://kvittering.online.ntnu.no" \
          --exclude "*" \
          --include "*.css" \
          --content-type "text/css"
        aws s3 sync apps/kvittering-frontend/dist "s3://kvittering.online.ntnu.no" \
          --exclude "*" \
          --include "*.js" \
          --content-type "application/javascript"
        aws s3 sync apps/kvittering-frontend/dist "s3://kvittering.online.ntnu.no" \
          --exclude "*" \
          --include "*.svg" \
          --content-type "image/svg+xml"
        aws s3 sync apps/kvittering-frontend/dist "s3://kvittering.online.ntnu.no" \
          --exclude "*.html" \
          --exclude "*.css" \
          --exclude "*.js" \
          --exclude "*.svg"
        aws cloudfront create-invalidation --distribution-id E2N69L93VKLW9F --paths '/*'
