-- AlterEnum
ALTER TYPE "task_type" ADD VALUE 'SEND_NOTIFICATION_EVENT_REGISTRATION';
ALTER TYPE "task_type" ADD VALUE 'SEND_NOTIFICATION_EVENT_REMINDER';
ALTER TYPE "task_type" ADD VALUE 'SEND_NOTIFICATION_JOB_LISTING_REMINDER';
