serve:
  cookies:
    same_site_mode: Lax

urls:
  self:
    issuer: http://127.0.0.1:4444
  consent: http://127.0.0.1:3000/api/oauth2/consent
  login: http://127.0.0.1:3000/api/oauth2/login
<<<<<<< Updated upstream
  logout: http://127.0.0.1:3000/auth/logout
=======
  logout: http://127.0.0.1:3000/sign-out
>>>>>>> Stashed changes

secrets:
  system:
    - youReallyNeedToChangeThis

oidc:
  subject_identifiers:
    supported_types:
      - pairwise
      - public
    pairwise:
      salt: youReallyNeedToChangeThis
