name: Build & deploy monoweb/rif
inputs:
  git-hash:
    description: 'Git hash to build'
    required: true
  deploy:
    description: 'Deploy the built image to AWS ECS'
    required: false
    default: false
  environment:
    description: 'Environment to deploy to. Only required if deploy is true'
    required: false
runs:
  using: composite
  steps:
    - name: Install local GitHub Actions
      uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      with:
        fetch-depth: 1
        sparse-checkout: '.github'
        sparse-checkout-cone-mode: true
    - uses: ./.github/actions/internal/doppler-secrets
      id: acquire-secrets
      with:
        project: monoweb-rif
        config: ${{ inputs.environment }}
    - uses: ./.github/actions/internal/docker-build
      id: build
      with:
        aws-region: 'eu-north-1'
        aws-iam-role: arn:aws:iam::891459268445:role/monoweb-${{ inputs.environment }}-rif-ci-role
        aws-ecr-repository: 891459268445.dkr.ecr.eu-north-1.amazonaws.com/monoweb/${{ inputs.environment }}/rif
        git-hash: ${{ inputs.git-hash }}
        dockerfile: apps/rif/Dockerfile
        build-arguments: ${{ steps.acquire-secrets.outputs.secrets }}
        push: ${{ inputs.deploy }}
    - uses: ./.github/actions/internal/aws-ecs-deploy
      if: ${{ inputs.deploy == 'true' }}
      id: deploy
      with:
        aws-region: 'eu-north-1'
        aws-iam-role: arn:aws:iam::891459268445:role/monoweb-${{ inputs.environment }}-rif-ci-role
        aws-task-definition-arn: arn:aws:ecs:eu-north-1:891459268445:task-definition/monoweb-${{ inputs.environment }}-rif
        cluster-name: evergreen-prod-cluster
        service-name: monoweb-${{ inputs.environment }}-rif
        container-name: monoweb-${{ inputs.environment }}-rif
        image: ${{ steps.build.outputs.image }}
