import ContentList from "./ContentList";
import ContentListItem from "./ContentListItem";
import DebugLink from "./DebugLink";
import NavigationMenuViewport from "./NavigationMenuViewport";
import Link from "./Link";
import Menu from "./Menu";
import List from "./List";
import IndicatorWithArrow from "./IndicatorWithArrow";
import TriggerWithCaret from "./Trigger";
import Content from "./Content";

export const DesktopList = ContentList;
export const DesktopNavbarContainer = Menu;
export const NavigationMenuContent = Content;
export const NavigationMenuLink = Link;
export const NavigationMenuTrigger = TriggerWithCaret;
export const DropdownIndicator = IndicatorWithArrow;
export const NavigationMenuList = List;
export const DesktopViewport = NavigationMenuViewport;
export const DesktopListItem = ContentListItem;
export const DebugCard = DebugLink;
