import { Metadata } from "next"
import { PropsWithChildren } from "react"
import "../root.css"

export const metadata: Metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
}

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
