name: Acquire secrets from Doppler
description: |
  Acquired the secrets from Doppler and sets them as environment variables.
  
  Requires the parent workflow to have `write` permissions for `id-token`. and
  `read` permissions for `contents`.
inputs:
  project:
    description: The Doppler project to use
    required: true
  config:
    description: The Doppler config to use
    required: true
outputs:
  secrets:
    description: The secrets acquired from Doppler
    value: ${{ steps.export.outputs.SECRETS }}
runs:
  using: composite
  steps:
    - name: Acquire GitHub OpenID Connect token
      uses: actions/github-script@v7
      id: get-oidc-token
      with:
        script: core.setOutput('oidc_token', await core.getIDToken())
    - name: Install Doppler CLI
      uses: dopplerhq/cli-action@v3
    - name: Login to Doppler
      shell: bash
      run: |
        doppler oidc login \
        --api-host https://api.doppler.com \
        --scope=. \
        --identity=8f25d2a1-28b9-4f2a-8fb3-115b10f456b2 \
        --token=${{ steps.get-oidc-token.outputs.oidc_token }}
    - name: Export secrets from Doppler to GitHub
      id: export
      shell: bash
      run: |
        # Define variables to exclude and variables to not mask
        excluded_vars='["OTEL_EXPORTER_OTLP_ENDPOINT", "OTEL_EXPORTER_OTLP_HEADERS", "OTEL_EXPORTER_OTLP_PROTOCOL"]'
        no_mask_vars='["DOPPLER_PROJECT", "DOPPLER_CONFIG", "DOPPLER_ENVIRONMENT"]'
        
        # Export secrets with masking (excluding OTEL vars and not masking Doppler config vars)
        doppler secrets --project "${{ inputs.project }}" --config "${{ inputs.config }}" --json | \
        jq -r --argjson excluded "$excluded_vars" --argjson no_mask "$no_mask_vars" '
        to_entries |
        map(select(.key as $k | $excluded | index($k) | not)) |
        map(
        if (.key as $k | $no_mask | index($k))
        then "echo \(.key)=\(.value.computed) >> $GITHUB_ENV"
        else "echo \"::add-mask::\(.value.computed)\"\necho \(.key)=\(.value.computed) >> $GITHUB_ENV"
        end
        ) |
        .[]' | \
        bash
    
        # Export to GitHub output (excluding OTEL vars)
        echo "SECRETS<<EOF" >> $GITHUB_OUTPUT
        doppler secrets --project "${{ inputs.project }}" --config "${{ inputs.config }}" --json | \
        jq -r --argjson excluded "$excluded_vars" '
        to_entries |
        map(select(.key as $k | $excluded | index($k) | not)) |
        map("\(.key)=\(.value.computed)") |
        .[]' >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
