#!/usr/bin/env just --justfile
export PATH := "./node_modules/.bin:" + env_var('PATH')

build env:
  docker build --platform linux/amd64 -t grades-backend:latest -f Dockerfile ../..

push env:
  docker tag grades-backend:latest 891459268445.dkr.ecr.eu-north-1.amazonaws.com/monoweb/{{env}}/grades-backend:latest
  docker push 891459268445.dkr.ecr.eu-north-1.amazonaws.com/monoweb/{{env}}/grades-backend:latest

release env: (build env) (push env)
