name: Build & deploy monoweb/rpc
inputs:
  git-hash:
    description: 'Git hash to build'
    required: true
  deploy:
    description: 'Deploy the built image to AWS ECS'
    required: false
    default: false
  environment:
    description: 'Environment to deploy to. Only required if deploy is true'
    required: false
runs:
  using: composite
  steps:
    - name: Install local GitHub Actions
      uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      with:
        fetch-depth: 1
        sparse-checkout: '.github'
        sparse-checkout-cone-mode: true
    - uses: ./.github/actions/internal/docker-build
      id: build
      with:
        aws-region: 'eu-north-1'
        aws-iam-role: arn:aws:iam::891459268445:role/monoweb-${{ inputs.environment }}-rpc-ci-role
        aws-ecr-repository: 891459268445.dkr.ecr.eu-north-1.amazonaws.com/monoweb/${{ inputs.environment }}/rpc
        git-hash: ${{ inputs.git-hash }}
        dockerfile: apps/rpc/Dockerfile
        push: ${{ inputs.deploy }}
        build-arguments: |
          SENTRY_RELEASE=git-${{ inputs.git-hash }}-${{ inputs.environment }}
    - uses: ./.github/actions/internal/aws-ecs-deploy
      if: ${{ inputs.deploy == 'true' }}
      id: deploy
      with:
        aws-region: 'eu-north-1'
        aws-iam-role: arn:aws:iam::891459268445:role/monoweb-${{ inputs.environment }}-rpc-ci-role
        aws-task-definition-arn: arn:aws:ecs:eu-north-1:891459268445:task-definition/monoweb-${{ inputs.environment }}-rpc
        cluster-name: evergreen-prod-cluster
        service-name: monoweb-${{ inputs.environment }}-rpc
        container-name: monoweb-${{ inputs.environment }}-rpc
        image: ${{ steps.build.outputs.image }}
