name: Build & deploy monoweb/splash-2025
inputs:
  deploy:
    description: 'Deploy the built site to AWS S3'
    required: false
    default: false
runs:
  using: composite
  steps:
    - name: Install local GitHub Actions
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        sparse-checkout: '.github'
        sparse-checkout-cone-mode: true
    - uses: ./.github/actions/internal/doppler-secrets
      id: acquire-secrets
      with:
        project: monoweb-splash-frontend
        config: prd

    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - uses: pnpm/action-setup@v2
      with:
        version: 9.15.7
    - uses: actions/setup-node@v4
      with:
        node-version: 22.14.0
        cache: 'pnpm'
    - name: Build frontend
      shell: bash
      working-directory: apps/splash-2025
      run: doppler run -p monoweb-splash-frontend -c prd -- pnpm build

    - name: Deploy to S3
      if: ${{ inputs.deploy == 'true' }}
      shell: bash
      run: |
        aws s3 sync apps/splash-2025/dist "s3://splash.online.ntnu.no" \
          --exclude "*" \
          --include "*.html" \
          --content-type "text/html"
        aws s3 sync apps/splash-2025/dist "s3://splash.online.ntnu.no" \
          --exclude "*" \
          --include "*.css" \
          --content-type "text/css"
        aws s3 sync apps/splash-2025/dist "s3://splash.online.ntnu.no" \
          --exclude "*" \
          --include "*.js" \
          --content-type "application/javascript"
        aws s3 sync apps/splash-2025/dist "s3://splash.online.ntnu.no" \
          --exclude "*" \
          --include "*.svg" \
          --content-type "image/svg+xml"
        aws s3 sync apps/splash-2025/dist "s3://splash.online.ntnu.no" \
          --exclude "*.html" \
          --exclude "*.css" \
          --exclude "*.js" \
          --exclude "*.svg"
        aws cloudfront create-invalidation --distribution-id E3J930LEDCHBY3 --paths '/*'
