export { createTemplate, InvalidTemplateArguments } from "./template"
export type { Template, TemplateProps } from "./template"
export { Template as HelloWorldTemplate } from "./emails/hello-world"
export { Template as InterestFormForBedkomTemplate } from "./emails/interest-form-for-bedkom"
export { Template as InterestFormForCompanyTemplate } from "./emails/interest-form-for-company"
export { Template as InvoiceFormForBedKomTemplate } from "./emails/invoice-form-for-bedkom"
