name: Build & deploy monoweb/kvittering-backend
inputs:
  git-hash:
    description: 'Git hash to build'
    required: true
  deploy:
    description: 'Deploy the built image to AWS ECS'
    required: false
    default: false
runs:
  using: composite
  steps:
    - name: Install local GitHub Actions
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        sparse-checkout: '.github'
        sparse-checkout-cone-mode: true
    - uses: ./.github/actions/internal/docker-build
      id: build
      with:
        aws-region: 'eu-north-1'
        aws-iam-role: arn:aws:iam::891459268445:role/monoweb-prd-kvittering-backend-ci-role
        aws-ecr-repository: 891459268445.dkr.ecr.eu-north-1.amazonaws.com/monoweb/prd/kvittering-backend
        git-hash: ${{ inputs.git-hash }}
        dockerfile: apps/kvittering-backend/Dockerfile
        push: ${{ inputs.deploy }}
    - uses: ./.github/actions/internal/aws-ecs-deploy
      if: ${{ inputs.deploy == 'true' }}
      id: deploy
      with:
        aws-region: 'eu-north-1'
        aws-iam-role: arn:aws:iam::891459268445:role/monoweb-prd-kvittering-backend-ci-role
        aws-task-definition-arn: arn:aws:ecs:eu-north-1:891459268445:task-definition/monoweb-prod-kvittering-backend
        cluster-name: evergreen-prod-cluster
        service-name: monoweb-prod-kvittering-backend
        container-name: monoweb-prod-kvittering-backend
        image: ${{ steps.build.outputs.image }}
