name: Docker build
description: Docker build support with automatic push to AWS ECR
inputs:
  git-hash:
    description: 'Git sha256 hash to build'
    required: true
  build-arguments:
    description: 'Docker build arguments'
    required: false
  dockerfile:
    description: 'Dockerfile to use for build'
    required: true
  push:
    description: 'Push the image to ECR'
    required: false
    default: false
  aws-ecr-repository:
    description: 'AWS ECR Repository to push to. Will create :latest and :sha tags'
    required: true
  aws-iam-role:
    description: 'IAM role to assume for AWS ECR push'
    required: true
  aws-region:
    description: 'AWS Region to use'
    required: true
    default: 'eu-north-1'
outputs:
  image:
    description: 'The Docker tag containing the git hash that was built'
    value: ${{ inputs.aws-ecr-repository }}:git-${{ inputs.git-hash }}
runs:
  using: composite
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4
      with:
        aws-region: ${{ inputs.aws-region }}
        role-to-assume: ${{ inputs.aws-iam-role }}
    - name: Login to AWS ECR
      uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2
    - name: Check out provided ref
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      with:
        fetch-depth: 1
        ref: ${{ inputs.git-hash }}
    - name: Build docker image
      uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
      with:
        platforms: linux/amd64
        context: .
        file: ${{ inputs.dockerfile }}
        tags: ${{ inputs.aws-ecr-repository }}:latest, ${{ inputs.aws-ecr-repository }}:git-${{ inputs.git-hash }}
        build-args: ${{ inputs.build-arguments }}
        push: ${{ inputs.push }}
